### ISSUE TITLE
Change of Expo.io "owner" key

### ISSUE THREAD

**Issue by dkastl** [consento-org/rn-tape#14]
We switched the account on Expo.io, so now the `owner` key should be set to `grp`.
https://github.com/consento-org/mobile/blob/next/app.json#L7

If not specified it will use the default "owner` name configured with Expo.

**Comment by martinheidegger** [comment]
Actually the whole set of properties need to become options for `rn-tape` that are available either as cli input or environment variable.

https://github.com/consento-org/mobile/blob/b16b94538038bb3451916ad87e0850f748f87af9/app.json#L5-L8

**Comment by martinheidegger** [comment]
@dkastl This is an issue of `consento/mobile` and not of `rn-tape`, right? :thinking:

**Comment by dkastl** [comment]
Eventually yes, but I saw rn-tape build on Consento's Expo.io dashboard, and three repositories had the environment secret variable enabled. 

Then I saw app.json in this repository and created the issue. But feel free to close it, if doesn't apply.

**Comment by dkastl** [comment]
If this not an issue of `rn-tape`, why does this happen then?
https://expo.io/dashboard/grp/expotape

It seems to come from the repository:
https://github.com/consento-org/rn-tape/tree/master/expotape

**Comment by martinheidegger** [comment]
The `rn-tape` builds are currently used in the [`get-random-bytes-polypony`](https://github.com/consento-org/get-random-values-polypony) repository and the credentials are setup in the workflow script of the mobile repo. This is an issue of the credentials used in that process but not by rn-tape.
